//
//  Workspace.swift
//  SmartHomeManifests
//
//  Created by 김동준 on 2/15/25
//

import ProjectDescription

let workspace = Workspace(
    name: "App",
    projects: [
        "Projects/**"
    ],
    generationOptions: .options(autogeneratedWorkspaceSchemes: .disabled)
)
